# Generated by Django 3.0.8 on 2020-07-09 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infobase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='amount',
        ),
        migrations.AddField(
            model_name='entry',
            name='c_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='p_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='quality',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
