# Generated by Django 3.0.8 on 2020-07-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infobase', '0003_auto_20200709_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='summary',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
