# Generated by Django 3.0.8 on 2020-07-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infobase', '0005_auto_20200709_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
