# Generated by Django 3.0.8 on 2020-07-11 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('infobase', '0006_auto_20200709_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='userkey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
            preserve_default=False,
        ),
    ]
