# Generated by Django 3.0.8 on 2020-07-11 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('infobase', '0007_entry_userkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='userkey',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
    ]
