# Generated by Django 3.0.8 on 2020-07-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infobase', '0011_auto_20200711_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='userkey',
            new_name='user',
        ),
    ]
