# Generated by Django 3.0.8 on 2020-07-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap', '0003_tdee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdee',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tdee',
            name='feet',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tdee',
            name='inches',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tdee',
            name='sex',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tdee',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
