# Generated by Django 3.0.8 on 2020-07-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
